

services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped