server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:401b461234567890abcdef1234567890abcdef1234567890abcdef1234567890}

spring:
  application:
    name: api-gateway-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/api_gateway_db}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      routes:
        - id: user_service
          uri: lb://${USER_SERVICE_NAME:USER-SERVICE}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: AuthenticationFilter
            - name: MongoRateLimiterFilter
            - name: GatewayAuditFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@apiKeyResolver}"
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/users

        - id: product_service
          uri: lb://${PRODUCT_SERVICE_NAME:PRODUCT-SERVICE}
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: AuthenticationFilter
            - name: MongoRateLimiterFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@apiKeyResolver}"
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/products
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
      productServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
  timelimiter:
    instances:
      userServiceCircuitBreaker:
        timeoutDuration: 2s
      productServiceCircuitBreaker:
        timeoutDuration: 2s

management:
  health:
    circuitbreakers:
      enabled: true
    discovery:
      enabled: false
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URI:http://localhost:9411/api/v2/spans}

logging:
  pattern:
    console: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"
  level:
    org.springframework.cloud.gateway: DEBUG
    io.micrometer.tracing: DEBUG